name: Main Workflow
on:
  workflow_dispatch:

jobs:
  call-reusable-workflow:
    strategy:
      matrix:
        node-version: [14, 16, 18, 20]

    uses: ./.github/workflows/reusable-workflow.yaml
    with:
      node: ${{ matrix.node-version }}


  print-gcloud-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          gcloudVersion=$(gcloud version 2> /dev/null | grep "Google Cloud SDK" | cut -d ' ' -f 4)
          echo "$gcloudVersion"


  call-dynamic-names-workflow:
    uses: ./.github/workflows/reusable-dynamic-names-workflow.yaml
    with:
      workflow_name: Foobar Workflow
      build_type: linux
      version: 42


  matrix-job:
    name: ${{ matrix.name }} Job
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        project-path: [apps/client, apps/server]
        include:
          - project-path: apps/client
            name: Admin Client
          - project-path: apps/server
            name: Admin API

    steps:
      - uses: actions/checkout@v3
      - run: |
          echo "${{ matrix.project-path }} | ${{ matrix.name }}"


  include-only-matrix-job:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        include:
          - project-path: apps/client
            name: Admin Client
          - project-path: apps/server
            name: Admin API

    steps:
      - uses: actions/checkout@v3
      - run: |
          echo "${{ matrix.project-path }} | ${{ matrix.name }}"


  upload-artifact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: mkdir dist && cp -r apps dist
      - uses: actions/upload-artifact@v3
        with:
          name: projects
          path: dist
          if-no-files-found: error
      - run: tree


  download-artifact:
    needs: upload-artifact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: projects
          path: artifacts
      - run: tree


  call-reusable-workflow-using-script:
    uses: ./.github/workflows/reusable-workflow-using-script.yaml
    with:
      value: 42


  messages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "::group::Message Group"
      - run: echo "::debug::Some Debug Message"
      - run: echo "::notice title=My Notice::Some notice info"
      - run: echo "::warning title=My Warning::Some warning info"
      - run: echo "::error title=My Error::Some error info"
      - run: echo "Regular message"
      - run: echo "::endgroup::"

  job-summary:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "### Hello World! :rocket:" >> $GITHUB_STEP_SUMMARY

  step-output:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: one
        run: echo "my-value=foobar" >> $GITHUB_OUTPUT
      - id: two
        run: echo "my-value => ${{ steps.one.outputs.my-value }}"

  process-bash-associative-arrays:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          declare -A client=(
            [id]='project-client'
            [name]='client'
            [path]='apps/client'
          )
          declare -A server=(
            [id]='project-server'
            [name]='server'
            [path]='apps/server'
          )

          apps=(client server)
          declare -n app
          for app in "${apps[@]}"; do
              echo "ID: ${app[id]}"
              echo "Name: ${app[name]}"
              echo "Path: ${app[path]}"
              echo ""
          done
