name: Main Workflow
on:
  workflow_dispatch:

jobs:
  call-reusable-workflow:
    strategy:
      matrix:
        node-version: [14, 16, 18, 20]

    uses: ./.github/workflows/reusable-workflow.yaml
    with:
      node: ${{ matrix.node-version }}

  print-gcloud-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          gcloudVersion=$(gcloud version 2> /dev/null | grep "Google Cloud SDK" | cut -d ' ' -f 4)
          echo "$gcloudVersion"

  call-dynamic-names-workflow:
    uses: ./.github/workflows/reusable-dynamic-names-workflow.yaml
    with:
      workflow_name: Foobar Workflow
      build_type: linux
      version: 42
