name: Main Workflow
on:
  workflow_dispatch:

jobs:
  call-reusable-workflow:
    strategy:
      matrix:
        node-version: [14, 16, 18, 20]

    uses: ./.github/workflows/reusable-workflow.yaml
    with:
      node: ${{ matrix.node-version }}


  print-gcloud-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          gcloudVersion=$(gcloud version 2> /dev/null | grep "Google Cloud SDK" | cut -d ' ' -f 4)
          echo "$gcloudVersion"


  call-dynamic-names-workflow:
    uses: ./.github/workflows/reusable-dynamic-names-workflow.yaml
    with:
      workflow_name: Foobar Workflow
      build_type: linux
      version: 42


  matrix-job:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        project-path: [apps/client, apps/server]
        include:
          - project-path: apps/client
            name: Admin Client
          - project-path: apps/server
            name: Admin API

    steps:
      - uses: actions/checkout@v3
      - run: |
          echo "${{ matrix.project-path }} | ${{ matrix.name }}"


  include-only-matrix-job:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        include:
          - project-path: apps/client
            name: Admin Client
          - project-path: apps/server
            name: Admin API

    steps:
      - uses: actions/checkout@v3
      - run: |
          echo "${{ matrix.project-path }} | ${{ matrix.name }}"


  upload-artifact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: mkdir dist && cp -r apps dist
      - uses: actions/upload-artifact@v3
        with:
          name: projects
          path: dist
          if-no-files-found: error
      - run: tree


  download-artifact:
    needs: upload-artifact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: projects
          path: artifacts
      - run: tree

  call-reusable-workflow-using-script:
    uses: ./.github/workflows/reusable-workflow-using-script.yaml
    with:
      value: 42
