name: Reusable Workflow
on:
  workflow_call:
    inputs:
      node:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Output the input value
        run: |
          echo "(build): The node version to use is: ${{ inputs.node }}"

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Output the input value
        run: |
          echo "(deploy): The node version to use is: ${{ inputs.node }}"
