name: Dynamic Names Reusable Workflow
run-name: ${{ inputs.workflow_name }}

on:
  workflow_call:
    inputs:
      workflow_name:
        required: true
        type: string
      build_type:
        required: true
        type: string
      version:
        required: true
        type: string

jobs:
  build:
    name: Build (${{ inputs.build_type }})
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          echo "(build): The version to use is: ${{ inputs.version }}"

  deploy:
    name: Deploy (${{ inputs.build_type }})
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          echo "(deploy): The version to use is: ${{ inputs.version }}"
